# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Katharina Killy
subtitle:
# description: Use language files
author: Katharina Killy
language: de
keywords: "Psychologie, Kindergarten, Psychologische Beratung, Elternberatung, Erziehungsberatung, Entwicklungsdiagnostik, Schulreife, Entwicklungsförderung, Online Beratung, Entspannungsgruppe, pädagogische Fachkräfte, Supervision, Elternbildung, Elternabend, psychology, kindergarten, nursery, counseling, parental counseling, child guidance, diagnostic of child development and school readiness, development furtherance, online counseling, relaxation group, supervision, parent education, parents evening"

open_graph:
  image: /img/logo.png

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://www.killy.at
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public

# Writing
new_post_name: :title.md # File name of new posts
default_layout: page
relative_link: false

date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:andre-pt/killy-at.git
  branch: gh-pages

theme: stanley

sitemap:
  path: sitemap.xml

html_minifier:
  removeComments: true
  removeCommentsFromCDATA: true
  removeCDATASectionsFromCDATA: true
  collapseWhitespace: true
  conservativeCollapse: true
  preserveLineBreaks: false
  collapseBooleanAttributes: true
  removeAttributeQuotes: false
  removeRedundantAttributes: true
  preventAttributesEscaping: false
  useShortDoctype: false
  removeEmptyAttributes: true
  removeScriptTypeAttributes: false
  removeStyleLinkTypeAttributes: false
  removeOptionalTags: false
  removeIgnored: true
  removeEmptyElements: false # This appears to break if set to true
  lint: false
  keepClosingSlash: false
  caseSensitive: false
  minifyJS: true
  minifyCSS: true
  minifyURLs: false

imagemin:
  enable     : true
  interlaced : true
  multipass  : true
  optimizationLevel: 2
  pngquant   : true
  progressive: true
